
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62812
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //===============function===============
    
    public void ItemCost()
    {
        double sum = 0;
        
         for (int i = 0; i < jTable1.getRowCount(); i++)
         {
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
             
         }
         jtxtSubTotal.setText(Double.toString(sum));
         double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
         
         double cTax = (cTotal1 * 3.9)/100;
         String iTaxTotal = String.format("$ %.2f", cTax);
         jtxtTax.setText(iTaxTotal);
         
          String iSubTotal = String.format("$ %.2f", cTotal1);
         jtxtSubTotal.setText(iSubTotal);
         
         String iTotal = String.format("$ %.2f", cTotal1 + cTax);
         jtxtTotal.setText(iTotal);
         
          String BarCode = String.format("Total is %.2f", cTotal1 + cTax);
         jtxtBarCode.setText(BarCode);
         
         
    }
    
     //===============function Changer ===============
    
    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
         for (int i = 0; i < jTable1.getRowCount(); i++)
         {
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
             
         }
         double cTax = (sum * 3.9)/100;
         double cChange = (cash - (sum + cTax));
         
         String ChangeGiven = String.format("$ %.2f", cChange);
         jtxtChange.setText(ChangeGiven);
         
        
    }
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnMangga = new javax.swing.JButton();
        jbtnTeh = new javax.swing.JButton();
        jbtnGreen = new javax.swing.JButton();
        jbtnBoba = new javax.swing.JButton();
        jbtnCola = new javax.swing.JButton();
        jbtnCope = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jbtnSalad = new javax.swing.JButton();
        jbtnRainBowCake = new javax.swing.JButton();
        jbtnCincau = new javax.swing.JButton();
        jbtnCoklat = new javax.swing.JButton();
        jbtnBobaMilk = new javax.swing.JButton();
        jbtnCendol = new javax.swing.JButton();
        jbtnJuice = new javax.swing.JButton();
        jbtnJeruk = new javax.swing.JButton();
        jbtnMojito = new javax.swing.JButton();
        jbtnHerbal = new javax.swing.JButton();
        jbtnWaterMelon = new javax.swing.JButton();
        jbtnGula = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtntitik = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbtnPay = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnMangga.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/6.jpeg"))); // NOI18N
        jbtnMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnManggaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMangga, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 130, 100));

        jbtnTeh.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnTeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.jpeg"))); // NOI18N
        jbtnTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTehActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 100));

        jbtnGreen.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpeg"))); // NOI18N
        jbtnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGreenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 100));

        jbtnBoba.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbtnBoba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.jpeg"))); // NOI18N
        jbtnBoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBobaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBoba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 100));

        jbtnCola.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.jpeg"))); // NOI18N
        jbtnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 100));

        jbtnCope.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCope.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5.jpeg"))); // NOI18N
        jbtnCope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCopeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCope, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 100));

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton19.setText("7");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 100));

        jbtnSalad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSalad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/7.jpeg"))); // NOI18N
        jbtnSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaladActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 100));

        jbtnRainBowCake.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRainBowCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/8.jpeg"))); // NOI18N
        jbtnRainBowCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRainBowCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRainBowCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, 100));

        jbtnCincau.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCincau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/9.jpeg"))); // NOI18N
        jbtnCincau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCincauActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCincau, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 100));

        jbtnCoklat.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCoklat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10.jpeg"))); // NOI18N
        jbtnCoklat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoklatActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoklat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 130, 100));

        jbtnBobaMilk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBobaMilk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/11.jpeg"))); // NOI18N
        jbtnBobaMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBobaMilkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBobaMilk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 100));

        jbtnCendol.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCendol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/12.jpeg"))); // NOI18N
        jbtnCendol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCendolActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCendol, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 130, 100));

        jbtnJuice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnJuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/18.jpeg"))); // NOI18N
        jbtnJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJuiceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 130, 100));

        jbtnJeruk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnJeruk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/15.jpeg"))); // NOI18N
        jbtnJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJerukActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnJeruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, 100));

        jbtnMojito.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMojito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/13.jpeg"))); // NOI18N
        jbtnMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMojitoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMojito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 100));

        jbtnHerbal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnHerbal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/17.jpeg"))); // NOI18N
        jbtnHerbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHerbalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHerbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 130, 100));

        jbtnWaterMelon.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnWaterMelon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/16.jpeg"))); // NOI18N
        jbtnWaterMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWaterMelonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnWaterMelon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 130, 100));

        jbtnGula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnGula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/14.jpeg"))); // NOI18N
        jbtnGula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGulaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 130, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" $ 2.57");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" $ 2.90");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" $ 2.78");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" $ 3.20");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 60, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" $ 3.75");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" $ 2.90");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 60, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" $ 2.90");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" $ 3.40");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" $ 3.95");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 60, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" $ 1.20");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 60, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" $ 2.99");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 60, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" $ 2.10");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 60, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" $ 2.10");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 60, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(" $ 2.75");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 60, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(" $ 2.30");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 60, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(" $ 1.70");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 60, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" $ 0.70");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 60, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(" $ 0.57");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 850, 470));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 100, 100));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 100));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 100));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 100));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 100));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, 100));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 100));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 100));

        jbtnc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnc.setText("C");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 100, 100));

        jbtntitik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtntitik.setText(".");
        jbtntitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntitikActionPerformed(evt);
            }
        });
        jPanel2.add(jbtntitik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 100));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 100));

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 490));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 330, 380));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("Tax");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setText("Sub Total");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setText("Total");

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnPay.setBackground(new java.awt.Color(51, 255, 51));
        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });

        jbtnReset.setBackground(new java.awt.Color(255, 204, 204));
        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPrint.setBackground(new java.awt.Color(51, 102, 255));
        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnRemove.setBackground(new java.awt.Color(255, 153, 51));
        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(255, 0, 0));
        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel4.setText("Payment Method");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel6.setText("Change");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel5.setText("Cash");

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jtxtDisplay))
                    .addComponent(jcboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboPayment))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1520, 210));

        jtxtBarCode.setFont(new java.awt.Font("3 of 9 Barcode", 0, 48)); // NOI18N
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 330, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
       
           String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn8.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
           String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn5.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn2.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtntitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntitikActionPerformed
       
        if(! jtxtDisplay.getText().contains(".")){
             jtxtDisplay.setText( jtxtDisplay.getText() + jbtntitik.getText());
        }
    }//GEN-LAST:event_jbtntitikActionPerformed

    private void jbtnBobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBobaActionPerformed
          double PriceofItem = 2.90;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Boba","1", PriceofItem});
        ItemCost();
                  
    }//GEN-LAST:event_jbtnBobaActionPerformed

    private void jbtnManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnManggaActionPerformed
            double PriceofItem = 2.90;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jus Mangga","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnManggaActionPerformed

    private void jbtnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColaActionPerformed
           double PriceofItem = 3.20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"CocaCola","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnColaActionPerformed

    private void jbtnCopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCopeActionPerformed
            double PriceofItem = 3.75;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Kopi Manis","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnCopeActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jbtnSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaladActionPerformed
            double PriceofItem = 2.90;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Salad Buah","1", PriceofItem});
        ItemCost();
    
    }//GEN-LAST:event_jbtnSaladActionPerformed

    private void jbtnCoklatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoklatActionPerformed
          double PriceofItem = 1.20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pop Ice Coklat","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnCoklatActionPerformed

    private void jbtnBobaMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBobaMilkActionPerformed
           double PriceofItem = 2.99;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Boba Milk","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnBobaMilkActionPerformed

    private void jbtnCendolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCendolActionPerformed
          double PriceofItem = 2.10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cendol Bali","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnCendolActionPerformed

    private void jbtnJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJuiceActionPerformed
            double PriceofItem = 0.75;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Juice Melon","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnJuiceActionPerformed

    private void jbtnMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMojitoActionPerformed
           double PriceofItem = 2.10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mojito","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnMojitoActionPerformed

    private void jbtnHerbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHerbalActionPerformed
           double PriceofItem = 0.70;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Herbal","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnHerbalActionPerformed

    private void jbtnWaterMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWaterMelonActionPerformed
            double PriceofItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Water Melon Juice","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnWaterMelonActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn9.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn6.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
           String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn1.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn1ActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
        
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jcboPayment.getSelectedItem().equals("Cash"))
            {
            Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                
            }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn7.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn4.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn3.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
           String Enternumber = jtxtDisplay.getText();
        
           if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());;
            
        }
           else{
               Enternumber = jtxtDisplay.getText() + jbtn0.getText();
               jtxtDisplay.setText(Enternumber);
           }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtnRainBowCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRainBowCakeActionPerformed
        
        double PriceofItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cendol Dawet","1", PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRainBowCakeActionPerformed

    private void jbtnCincauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCincauActionPerformed
            double PriceofItem = 3.95;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Cincau ","1", PriceofItem});
        ItemCost();
    
    }//GEN-LAST:event_jbtnCincauActionPerformed

    private void jbtnTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTehActionPerformed
            double PriceofItem = 2.78;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Teh Manis","1", PriceofItem});
        ItemCost();
                  
    }//GEN-LAST:event_jbtnTehActionPerformed

    private void jbtnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGreenActionPerformed
           double PriceofItem = 2.75;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Green Tea","1", PriceofItem});
        ItemCost();
    
    }//GEN-LAST:event_jbtnGreenActionPerformed

    private void jbtnGulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGulaActionPerformed
           double PriceofItem = 2.75;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Gula","1", PriceofItem});
        ItemCost();
                  
    }//GEN-LAST:event_jbtnGulaActionPerformed

    private void jbtnJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJerukActionPerformed
            double PriceofItem = 2.30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Es Jeruk","1", PriceofItem});
        ItemCost();
                   
    }//GEN-LAST:event_jbtnJerukActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtChange.setText("");
         jtxtTax.setText("");
          jtxtTotal.setText("");
           jtxtDisplay.setText("");
           jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0,number, integer} ");
        
        try{
        
            jTable1.print(JTable.PrintMode.NORMAL, header,footer);
        
        }
        
        catch(java.awt.print.PrinterException e){
        
            System.err.format("No Printer found", e.getMessage());
        
        }
            
        
       
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if(RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        
        ItemCost();
        if(jcboPayment.getSelectedItem().equals("Cash"))
            {
            Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                
            }
        
     
     
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBoba;
    private javax.swing.JButton jbtnBobaMilk;
    private javax.swing.JButton jbtnCendol;
    private javax.swing.JButton jbtnCincau;
    private javax.swing.JButton jbtnCoklat;
    private javax.swing.JButton jbtnCola;
    private javax.swing.JButton jbtnCope;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGreen;
    private javax.swing.JButton jbtnGula;
    private javax.swing.JButton jbtnHerbal;
    private javax.swing.JButton jbtnJeruk;
    private javax.swing.JButton jbtnJuice;
    private javax.swing.JButton jbtnMangga;
    private javax.swing.JButton jbtnMojito;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRainBowCake;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSalad;
    private javax.swing.JButton jbtnTeh;
    private javax.swing.JButton jbtnWaterMelon;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtntitik;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables

    private void getMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
